export type ImpostorCategory = {
  id: string;
  name: string;
  words: string[];
};

export const impostorCategories: ImpostorCategory[] = [
  {
    id: 'brands',
    name: 'Brands',
    words: [
      'Apple',
      'Samsung',
      'Nike',
      'Adidas',
      'Coca-Cola',
      'Pepsi',
      'Amazon',
      'Google',
      'Microsoft',
      'Tesla',
      'Toyota',
      'Honda',
      'Sony',
      'LG',
      'Intel',
      'IBM',
      'Dell',
      'HP',
      'Lenovo',
      'Uber',
      'Lyft',
      'Airbnb',
      'Netflix',
      'Disney',
      'Starbucks',
      "McDonald's",
      'Burger King',
      'Subway',
      'Target',
      'Walmart',
      'Costco',
      'IKEA',
      'Patagonia',
      'The North Face',
      'Under Armour',
      'Reebok',
      'New Balance',
      'Vans',
      'Puma',
      'H&M',
      'Zara',
      'Uniqlo',
      'Gucci',
      'Louis Vuitton',
      'Chanel',
      'Rolex',
      'Prada',
      'Hermes',
      'Burberry',
      'Cartier',
      'TikTok',
      'YouTube',
      'Spotify',
      'Adobe',
      'Salesforce',
      'Slack',
      'Shopify',
      'Square',
      'Stripe',
      'PayPal',
      'Visa',
      'Mastercard',
      'American Express',
      'FedEx',
      'UPS',
      'DHL',
      'Nvidia',
      'AMD',
      'ASUS',
      'Acer',
      'Razer',
      'Alienware',
      'Dyson',
      'Philips',
      'Nestle',
      'Heineken',
      'Lego',
      'Hasbro',
      'Ferrari',
      'BMW',
      'Mercedes-Benz',
      'Audi',
      'Volvo',
      'Hyundai',
      'Kia',
    ],
  },
  {
    id: 'colleges',
    name: 'Colleges',
    words: [
      'Harvard',
      'Stanford',
      'MIT',
      'UC Berkeley',
      'UCLA',
      'Yale',
      'Princeton',
      'Columbia',
      'Cornell',
      'Dartmouth',
      'Brown',
      'UPenn',
      'Caltech',
      'Carnegie Mellon',
      'Georgia Tech',
      'University of Michigan',
      'University of Texas',
      'NYU',
      'University of Washington',
      'UIUC',
      'Duke',
      'UNC Chapel Hill',
      'University of Virginia',
      'University of Florida',
      'USC',
      'UC Santa Barbara',
      'UC Irvine',
      'UC San Diego',
      'Purdue',
      'Wisconsin Madison',
      'Notre Dame',
      'Boston University',
      'Northwestern',
      'Rice',
      'Vanderbilt',
      'Emory',
      'Tulane',
      'University of Chicago',
      'Johns Hopkins',
      'Boston College',
      'University of Southern California',
      'Arizona State',
      'University of Arizona',
      'Ohio State',
      'Penn State',
      'Michigan State',
      'Rutgers',
      'University of Maryland',
      'University of Minnesota',
      'University of Colorado Boulder',
      'University of Oregon',
      'Oregon State',
      'Washington State',
      'Texas A&M',
      'Baylor',
      'SMU',
      'TCU',
      'University of Georgia',
      'Florida State',
      'Clemson',
      'Auburn',
      'LSU',
      'Ole Miss',
      'Alabama',
      'Tennessee',
      'Kansas',
      'Kansas State',
      'University of Missouri',
      'University of Kentucky',
      'University of Utah',
      'Brigham Young',
      'Colorado State',
    ],
  },
  {
    id: 'nba-players',
    name: 'NBA Players',
    words: [
      'LeBron James',
      'Stephen Curry',
      'Kevin Durant',
      'Giannis Antetokounmpo',
      'Nikola Jokic',
      'Luka Doncic',
      'Joel Embiid',
      'Jayson Tatum',
      'Kyrie Irving',
      'Damian Lillard',
      'Anthony Davis',
      'Jimmy Butler',
      'Kawhi Leonard',
      'Paul George',
      'James Harden',
      'Devin Booker',
      'Chris Paul',
      'Ja Morant',
      'Zion Williamson',
      'Trae Young',
      'Shai Gilgeous-Alexander',
      'Donovan Mitchell',
      'Karl-Anthony Towns',
      'LaMelo Ball',
      'Anthony Edwards',
      'DeMar DeRozan',
      'Draymond Green',
      'Klay Thompson',
      'Victor Wembanyama',
      'Chet Holmgren',
      'Scottie Barnes',
      'Tyrese Haliburton',
      'Bam Adebayo',
      'Rudy Gobert',
      'Jaylen Brown',
      'Jrue Holiday',
      'Khris Middleton',
      'Brandon Ingram',
      'CJ McCollum',
      'Zach LaVine',
      'Jamal Murray',
      'Michael Porter Jr.',
      'Aaron Gordon',
      'Pascal Siakam',
      'Fred VanVleet',
      'OG Anunoby',
      'DeAaron Fox',
      'Domantas Sabonis',
      'Jalen Brunson',
      'RJ Barrett',
      'Mikal Bridges',
      'Desmond Bane',
      'Darius Garland',
      'Evan Mobley',
      'Jarrett Allen',
      'Tyrese Maxey',
      'Kristaps Porzingis',
      'Bradley Beal',
      'Kyle Kuzma',
      'Franz Wagner',
      'Paolo Banchero',
      'Alperen Sengun',
      'Jalen Green',
      'Cade Cunningham',
      'Jaden Ivey',
      'Scoot Henderson',
      'Jabari Smith Jr.',
      'Jordan Poole',
      'Buddy Hield',
      'Malcolm Brogdon',
    ],
  },
  {
    id: 'countries',
    name: 'Countries',
    words: [
      'United States',
      'Canada',
      'Mexico',
      'Brazil',
      'Argentina',
      'United Kingdom',
      'France',
      'Germany',
      'Spain',
      'Italy',
      'Portugal',
      'Netherlands',
      'Sweden',
      'Norway',
      'Denmark',
      'Finland',
      'Poland',
      'Turkey',
      'Greece',
      'Russia',
      'India',
      'China',
      'Japan',
      'South Korea',
      'Vietnam',
      'Thailand',
      'Australia',
      'New Zealand',
      'South Africa',
      'Egypt',
      'Kenya',
      'Nigeria',
      'Saudi Arabia',
      'United Arab Emirates',
      'Qatar',
      'Kuwait',
      'Israel',
      'Jordan',
      'Lebanon',
      'Pakistan',
      'Bangladesh',
      'Sri Lanka',
      'Nepal',
      'Bhutan',
      'Myanmar',
      'Cambodia',
      'Malaysia',
      'Singapore',
      'Philippines',
      'Indonesia',
      'Laos',
      'Mongolia',
      'Uzbekistan',
      'Kazakhstan',
      'Turkmenistan',
      'Afghanistan',
      'Iraq',
      'Iran',
      'Syria',
      'Ethiopia',
      'Tanzania',
      'Uganda',
      'Ghana',
      'Ivory Coast',
      'Algeria',
      'Morocco',
      'Tunisia',
      'Chile',
      'Peru',
      'Colombia',
      'Venezuela',
      'Bolivia',
      'Paraguay',
      'Uruguay',
      'Panama',
      'Costa Rica',
      'Guatemala',
      'Honduras',
      'El Salvador',
      'Iceland',
      'Ireland',
      'Switzerland',
      'Austria',
    ],
  },
  {
    id: 'nintendo',
    name: 'Nintendo',
    words: [
      'Mario',
      'Luigi',
      'Princess Peach',
      'Yoshi',
      'Bowser',
      'Toad',
      'Link',
      'Zelda',
      'Ganondorf',
      'Samus Aran',
      'Kirby',
      'Donkey Kong',
      'Fox McCloud',
      'Captain Falcon',
      'Ness',
      'Pikachu',
      'Charizard',
      'Squirtle',
      'Jigglypuff',
      'Marth',
      'Roy',
      'Ike',
      'Villager',
      'Isabelle',
      'Tom Nook',
      'Inkling',
      'Ridley',
      'King K. Rool',
      'Meta Knight',
      'Wario',
      'Waluigi',
      'Rosalina',
      'Toadette',
      'Pauline',
      'Diddy Kong',
      'Dixie Kong',
      'Funky Kong',
      'Cranky Kong',
      'Luma',
      'Bowser Jr.',
      'Dry Bowser',
      'Birdo',
      'Daisy',
      'Tingle',
      'Sheik',
      'Impa',
      'Midna',
      'Wolf Link',
      'Epona',
      'Shulk',
      'Riki',
      'Fiora',
      'Pyra',
      'Mythra',
      'Chrom',
      'Robin',
      'Corrin',
      'Byleth',
      'Pit',
      'Palutena',
      'Dark Pit',
      'Little Mac',
      'Olimar',
      'Alph',
      'Mr. Game & Watch',
      'R.O.B.',
      'Duck Hunt',
      'Piranha Plant',
      'Min Min',
      'Banjo',
      'Kazooie',
      'Captain Olimar',
      'Zero Suit Samus',
      'Mewtwo',
      'Lucario',
      'Greninja',
    ],
  },
  {
    id: 'clash-royale',
    name: 'Clash Royale Cards',
    words: [
      'Archer Queen',
      'Skeleton King',
      'Golden Knight',
      'Monk',
      'Phoenix',
      'Goblin Giant',
      'Royal Giant',
      'Mega Knight',
      'P.E.K.K.A',
      'Sparky',
      'Lumberjack',
      'Electro Wizard',
      'Magic Archer',
      'Mother Witch',
      'Fisherman',
      'Royal Recruits',
      'Royal Hogs',
      'Battle Ram',
      'Ram Rider',
      'Hog Rider',
      'Giant Skeleton',
      'Balloon',
      'Miner',
      'Graveyard',
      'X-Bow',
      'Mortar',
      'Cannon Cart',
      'Elixir Golem',
      'Firecracker',
      'Mega Minion',
      'Baby Dragon',
      'Inferno Dragon',
      'Hunter',
      'Musketeer',
      'Bowler',
      'Wizard',
      'Ice Wizard',
      'Electro Spirit',
      'Ice Spirit',
      'Heal Spirit',
      'Spear Goblins',
      'Goblin Gang',
      'Goblin Barrel',
      'Goblin Drill',
      'Goblin Cage',
      'Skeletons',
      'Skeleton Army',
      'Bomber',
      'Bomb Tower',
      'Cannon',
      'Tesla',
      'Zappies',
      'Sparky',
      'Zap',
      'Arrows',
      'Fireball',
      'Rocket',
      'Lightning',
      'Poison',
      'Freeze',
      'Clone',
      'Earthquake',
      'Rage',
      'Mirror',
      'Tornado',
      'Graveyard',
      'Barbarian Barrel',
      'Log',
      'Snowball',
      'Barbarians',
      'Elite Barbarians',
      'Dark Prince',
      'Prince',
      'Mini P.E.K.K.A',
      'Bandit',
      'Battle Healer',
      'Night Witch',
      'Witch',
      'Ice Golem',
      'Golem',
      'Knight',
      'Ice Knight',
      'Skeleton Dragons',
      'Baby Dragon',
      'Lava Hound',
      'Flying Machine',
      'Minions',
      'Minion Horde',
      'Bats',
      'Mega Minion',
      'Archers',
      'Three Musketeers',
      'Royal Delivery',
      'Royal Ghost',
      'Cannon Cart',
      'Dart Goblin',
      'Fire Spirits',
      'Furnace',
      'Inferno Tower',
      'Inferno Dragon',
      'Tesla',
      'Mortar',
      'Bomb Tower',
      'Cannon',
      'Elixir Collector',
      'Heal Spirit',
      'Ice Spirit',
      'Electro Spirit',
      'Battle Ram',
      'Magic Archer',
      'Royal Giant',
      'Giant',
      'Mighty Miner',
      'Skeleton King',
      'Monk',
      'Archer Queen',
      'Golden Knight',
      'Rascals',
      'Firecracker',
      'Skeleton Barrel',
      'Flying Machine',
      'Zappies',
      'Royal Recruits',
      'Royal Hogs',
      'Mortar',
      'X-Bow',
      'Sparky',
      'P.E.K.K.A',
      'Mega Knight',
      'Giant Skeleton',
      'Cannon Cart',
      'Goblin Hut',
      'Barbarian Hut',
      'Tombstone',
      'Inferno Tower',
      'Bomb Tower',
      'Tesla',
      'Cannon',
      'Mortar',
      'Goblin Cage',
      'Elixir Golem',
      'Electro Giant',
      'Royal Giant',
      'Giant',
      'Golem',
      'Lumberjack',
      'Executioner',
      'Valkyrie',
      'Musketeer',
      'Ice Wizard',
      'Wizard',
      'Mother Witch',
      'Hunter',
      'Dark Prince',
      'Prince',
      'Mini P.E.K.K.A',
      'Archers',
      'Ice Golem',
      'Valkyrie',
      'Musketeer',
      'Bowler',
      'Executioner',
      'Electro Wizard',
      'Magic Archer',
      'Bandit',
      'Royal Ghost',
      'Fisherman',
      'Ram Rider',
      'Battle Healer',
      'Flying Machine',
      'Firecracker',
      'Skeleton Dragons',
      'Electro Dragon',
      'Phoenix',
      'Night Witch',
      'Witch',
      'Bats',
      'Minions',
      'Minion Horde',
      'Lava Hound',
      'Balloon',
      'Baby Dragon',
      'Inferno Dragon',
      'Mega Minion',
      'Fire Spirits',
      'Ice Spirits',
      'Electro Spirits',
      'Skeletons',
      'Guards',
      'Goblin Gang',
      'Spear Goblins',
      'Dart Goblin',
      'Goblins',
      'Wall Breakers',
      'Skeleton Barrel',
      'Bomber',
      'Cannon Cart',
      'Mighty Miner',
    ],
  },
  {
    id: 'games',
    name: 'Games',
    words: [
      'The Legend of Zelda: Breath of the Wild',
      'Elden Ring',
      'God of War',
      'Hollow Knight',
      'Stardew Valley',
      'Fortnite',
      'Minecraft',
      'League of Legends',
      'Valorant',
      'Overwatch',
      'Apex Legends',
      'Call of Duty',
      'Counter-Strike',
      'Grand Theft Auto V',
      'Red Dead Redemption 2',
      'Super Smash Bros. Ultimate',
      'Animal Crossing: New Horizons',
      'Splatoon 3',
      'Mario Kart 8 Deluxe',
      'Super Mario Odyssey',
      'Baldurs Gate 3',
      'Hades',
      'Disco Elysium',
      'Celeste',
      'Portal 2',
      'Among Us',
      'Rocket League',
      'FIFA',
      'NBA 2K',
      'Civilization VI',
      'The Sims 4',
      'Terraria',
      'Rainbow Six Siege',
      'Monster Hunter Rise',
      'Monster Hunter World',
      'Final Fantasy VII Remake',
      'Final Fantasy XIV',
      'Mass Effect',
      'Dragon Age',
      'Skyrim',
      'Oblivion',
      'Fallout 4',
      'Fallout New Vegas',
      'Diablo IV',
      'Diablo III',
      'Path of Exile',
      'Dota 2',
      'Team Fortress 2',
      'Half-Life 2',
      'Bioshock',
      'Bioshock Infinite',
      'Borderlands 3',
      'Borderlands 2',
      'Destiny 2',
      'Sea of Thieves',
      'No Mans Sky',
      'Forza Horizon 5',
      'Gran Turismo 7',
      'Need for Speed Heat',
      'Assassins Creed Valhalla',
      'Assassins Creed Odyssey',
      'Far Cry 6',
      'Ghost of Tsushima',
      'Spider-Man 2',
      'Spider-Man Miles Morales',
      'Returnal',
      'Control',
      'Outer Wilds',
      'Dead Cells',
      'Slay the Spire',
      'Into the Breach',
      'Fire Emblem Three Houses',
      'XCOM 2',
      'Cities Skylines',
      'Factorio',
      'Satisfactory',
      'Deep Rock Galactic',
      'Payday 3',
      'Warframe',
    ],
  },
  {
    id: 'minecraft-blocks',
    name: 'Minecraft Blocks',
    words: [
      'Stone',
      'Cobblestone',
      'Dirt',
      'Grass Block',
      'Sand',
      'Gravel',
      'Oak Log',
      'Spruce Log',
      'Birch Log',
      'Jungle Log',
      'Acacia Log',
      'Dark Oak Log',
      'Mangrove Log',
      'Oak Planks',
      'Spruce Planks',
      'Birch Planks',
      'Sandstone',
      'Red Sandstone',
      'Brick Block',
      'Stone Bricks',
      'Cobblestone Stairs',
      'Glass',
      'Glass Pane',
      'Iron Ore',
      'Coal Ore',
      'Diamond Ore',
      'Gold Ore',
      'Emerald Ore',
      'Lapis Lazuli Ore',
      'Copper Ore',
      'Deepslate',
      'Obsidian',
      'Netherrack',
      'Nether Quartz Ore',
      'End Stone',
      'Redstone Ore',
      'Ancient Debris',
      'Crying Obsidian',
      'Basalt',
      'Smooth Basalt',
      'Blackstone',
      'Polished Blackstone',
      'Glowstone',
      'Sea Lantern',
      'Prismarine',
      'Dark Prismarine',
      'Hay Bale',
      'Bookshelf',
      'Enchanting Table',
      'Anvil',
      'Smithing Table',
      'Crafting Table',
      'Furnace',
      'Blast Furnace',
      'Smoker',
      'Campfire',
      'Soul Campfire',
      'Bee Nest',
      'Beehive',
      'Honey Block',
      'Slime Block',
      'TNT',
      'Note Block',
      'Jukebox',
      'Glow Item Frame',
      'Torch',
      'Lantern',
      'Soul Lantern',
      'Amethyst Block',
      'Calcite',
      'Tuff',
      'Dripstone Block',
      'Pointed Dripstone',
      'Magma Block',
      'Shroomlight',
      'Warped Stem',
      'Crimson Stem',
      'Warped Nylium',
      'Crimson Nylium',
      'Warped Wart Block',
      'Nether Wart Block',
      'Sculk',
      'Sculk Sensor',
      'Sculk Catalyst',
      'Sculk Shrieker',
      'Frogspawn',
      'Reinforced Deepslate',
      'Cherry Log',
      'Cherry Planks',
      'Bamboo Block',
      'Bamboo Mosaic',
      'Bundle',
      'Moss Block',
      'Rooted Dirt',
      'Podzol',
      'Mycelium',
      'Snow Block',
      'Ice',
      'Packed Ice',
      'Blue Ice',
      'Nether Brick',
      'Quartz Block',
      'Smooth Quartz',
      'Terracotta',
      'Glazed Terracotta',
      'Concrete',
      'Concrete Powder',
      'Wool',
      'Carpet',
      'Leaves',
      'Cactus',
      'Sugar Cane',
      'Pumpkin',
      'Melon',
      'Kelp',
      'Seagrass',
      'Coral Block',
      'Warped Fungus',
      'Crimson Fungus',
      'Azalea',
      'Flowering Azalea',
      'Budding Amethyst',
      'Spore Blossom',
      'Pointed Dripstone',
      'Axolotl',
      'Creeper',
      'Zombie',
      'Skeleton',
      'Spider',
      'Enderman',
      'Warden',
      'Piglin',
      'Villager',
      'Witch',
      'Blaze',
      'Ghast',
      'Wither Skeleton',
      'Ender Dragon',
      'Bee',
      'Dolphin',
      'Goat',
      'Panda',
      'Camel',
      'Sniffer',
      'Allay',
      'Zombie Villager',
      'Husk',
      'Drowned',
      'Phantom',
      'Vex',
      'Evoker',
      'Vindicator',
      'Pillager',
      'Ravager',
      'Iron Golem',
      'Snow Golem',
      'Shulker',
      'Endermite',
      'Silverfish',
      'Slime',
      'Magma Cube',
      'Guardian',
      'Elder Guardian',
      'Squid',
      'Glow Squid',
      'Tropical Fish',
      'Pufferfish',
      'Salmon',
      'Cod',
      'Turtle',
      'Wolf',
      'Cat',
      'Ocelot',
      'Fox',
      'Polar Bear',
      'Horse',
      'Donkey',
      'Mule',
      'Llama',
      'Trader Llama',
      'Cow',
      'Mooshroom',
      'Pig',
      'Sheep',
      'Chicken',
      'Rabbit',
      'Bat',
      'Parrot',
      'Tadpole',
      'Frog',
      'Wither',
      'Ravager',
      'Piglin Brute',
      'Zoglin',
      'Hoglin',
      'Strider',
      'Mojang Plains Biome',
      'Desert Biome',
      'Savanna Biome',
      'Taiga Biome',
      'Jungle Biome',
      'Swamp Biome',
      'Mangrove Swamp',
      'Ice Spikes',
      'Deep Dark',
      'Cherry Grove',
      'Badlands',
      'Nether Wastes',
      'Basalt Deltas',
      'Crimson Forest',
      'Warped Forest',
      'End Highlands',
      'End Midlands',
      'Village',
      'Desert Temple',
      'Jungle Temple',
      'Witch Hut',
      'Ocean Monument',
      'Stronghold',
      'Mineshaft',
      'Dungeon',
      'Nether Fortress',
      'Bastion Remnant',
      'End City',
      'End Ship',
      'Ancient City',
      'Trail Ruins',
      'Pillager Outpost',
      'Woodland Mansion',
      'Buried Treasure',
      'Shipwreck',
      'Ocean Ruins',
      'Ruined Portal',
      'Nether Portal',
      'Igloo',
      'Desert Well',
      'Fossil',
      'Geode',
      'Amethyst Geode',
      'Mushroom Island',
      'Monument',
      'Fortress',
      'Bastion',
      'City',
      'Ship',
    ],
  },
  {
    id: 'fortnite',
    name: 'Fortnite (Chapter 1 Items & Places)',
    words: [
      'Assault Rifle',
      'Pump Shotgun',
      'Tactical Shotgun',
      'Hunting Rifle',
      'Bolt-Action Sniper',
      'Hand Cannon',
      'Minigun',
      'Grenade Launcher',
      'Rocket Launcher',
      'Boogie Bomb',
      'Chug Jug',
      'Slurp Juice',
      'Shield Potion',
      'Med Kit',
      'Bandages',
      'Launch Pad',
      'Spike Trap',
      'Port-a-Fort',
      'Drum Gun',
      'Compact SMG',
      'Burst Assault Rifle',
      'Suppressed SMG',
      'Scoped Assault Rifle',
      'Stink Bomb',
      'Impulse Grenade',
      'Rift-to-Go',
      'Guided Missile',
      'Heavy Shotgun',
      'Quadcrasher',
      'Baller',
      'Tilted Towers',
      'Pleasant Park',
      'Retail Row',
      'Salty Springs',
      'Lazy Lake',
      'Greasy Grove',
      'Tomato Town',
      'Dusty Depot',
      'Dusty Divot',
      'Fatal Fields',
      'Anarchy Acres',
      'Haunted Hills',
      'Snobby Shores',
      'Lonely Lodge',
      'Wailing Woods',
      'Paradise Palms',
      'Loot Lake',
      'Leaky Lake',
      'Flush Factory',
      'Moisty Mire',
      'Lucky Landing',
      'Polar Peak',
      'Frosty Flights',
      'Junk Junction',
      'Risky Reels',
      'Tilted Towers Neo',
      'Mega Mall',
      'Sunny Steps',
      'Volcano',
      'Rocket Silo',
      'The Block',
      'Grappler',
      'Shockwave Grenade',
      'Driftboard',
      'Bouncer',
      'C4 Remote Explosives',
      'Clinger',
      'Crossbow',
      'Scoped Revolver',
      'Dual Pistols',
      'Suppressed Pistol',
      'Heavy Sniper',
      'Thermal Scoped AR',
      'Light Machine Gun',
      'P90',
      'Tactical SMG',
      'Zapotron',
      'Mythic Goldfish',
      'Flint-Knock Pistol',
      'Proximity Grenade Launcher',
      'Storm Flip',
      'Junk Rift',
      'Shadow Bomb',
      'Port-a-Fortress',
      'Campfire',
      'Bush',
      'Slurp Truck',
      'Reboot Van',
      'Supply Llama',
      'Battle Bus',
      'Loot Llama',
      'Quad Launcher',
      'Heavy Assault Rifle',
      'Charge Shotgun',
      'Combat Shotgun',
      'Lever Action Shotgun',
      'Harpoon Gun',
      'Chiller Grenade',
    ],
  },
  {
    id: 'movies',
    name: 'Movies',
    words: [
      'The Shawshank Redemption',
      'The Godfather',
      'The Dark Knight',
      'Inception',
      'Interstellar',
      'Parasite',
      'Spirited Away',
      'The Lord of the Rings',
      'Star Wars',
      'The Matrix',
      'Pulp Fiction',
      'Fight Club',
      'Forrest Gump',
      'Titanic',
      'Avatar',
      'Gladiator',
      'Saving Private Ryan',
      'La La Land',
      'Whiplash',
      'The Social Network',
      'Everything Everywhere All at Once',
      'Mad Max: Fury Road',
      'Coco',
      'Inside Out',
      'Toy Story',
      'Finding Nemo',
      'Up',
      'The Lion King',
      'Frozen',
      'Black Panther',
      'Joker',
      'Dune',
      'Oppenheimer',
      'Barbie',
      'The Martian',
      'Blade Runner 2049',
      'Arrival',
      'The Prestige',
      'Memento',
      'The Departed',
      'Goodfellas',
      'Casino',
      'The Irishman',
      'The Pianist',
      'Schindlers List',
      'The Green Mile',
      'A Beautiful Mind',
      'Se7en',
      'Gone Girl',
      'Zodiac',
      'Shutter Island',
      'Inglourious Basterds',
      'Django Unchained',
      'Once Upon a Time in Hollywood',
      'No Country for Old Men',
      'There Will Be Blood',
      'The Big Short',
      'Moneyball',
      'Spotlight',
      'Birdman',
      'Moonlight',
      'Her',
      'Ex Machina',
      'Jojo Rabbit',
      'Knives Out',
      'Glass Onion',
      'Top Gun Maverick',
      'Mission Impossible Fallout',
      'John Wick',
      'John Wick 4',
      'The Bourne Identity',
      'Mad Max Fury Road',
      'Crouching Tiger Hidden Dragon',
      'Hero',
      'Spirited Away',
      'Your Name',
      'Perfect Blue',
      'The Incredibles',
      'Ratatouille',
      'Wall-E',
      'Up',
      'Howls Moving Castle',
      'Princess Mononoke',
    ],
  },
  {
    id: 'places',
    name: 'Places',
    words: [
      'New York City',
      'Los Angeles',
      'Paris',
      'London',
      'Tokyo',
      'Seoul',
      'Sydney',
      'Toronto',
      'Dubai',
      'Berlin',
      'Rome',
      'Barcelona',
      'San Francisco',
      'Chicago',
      'Hong Kong',
      'Singapore',
      'Bangkok',
      'Istanbul',
      'Mexico City',
      'Sao Paulo',
      'Buenos Aires',
      'Cape Town',
      'Nairobi',
      'Cairo',
      'Mumbai',
      'Delhi',
      'Jakarta',
      'Vancouver',
      'Boston',
      'Seattle',
      'Miami',
      'Austin',
      'Honolulu',
      'Lisbon',
      'Madrid',
      'Valencia',
      'Marseille',
      'Lyon',
      'Munich',
      'Frankfurt',
      'Hamburg',
      'Vienna',
      'Prague',
      'Budapest',
      'Warsaw',
      'Krakow',
      'Zurich',
      'Geneva',
      'Copenhagen',
      'Stockholm',
      'Oslo',
      'Helsinki',
      'Tallinn',
      'Riga',
      'Vilnius',
      'Athens',
      'Santorini',
      'Reykjavik',
      'Edinburgh',
      'Dublin',
      'Belfast',
      'Brussels',
      'Amsterdam',
      'Rotterdam',
      'Cape Town',
      'Johannesburg',
      'Casablanca',
      'Doha',
      'Abu Dhabi',
      'Kuala Lumpur',
      'Manila',
      'Ho Chi Minh City',
      'Hanoi',
      'Chiang Mai',
      'Phuket',
      'Queenstown',
      'Auckland',
      'Wellington',
      'Ottawa',
      'Montreal',
    ],
  },
  {
    id: 'foods',
    name: 'Foods',
    words: [
      'Pizza',
      'Sushi',
      'Hamburger',
      'Pasta',
      'Tacos',
      'Burrito',
      'Ramen',
      'Pad Thai',
      'Curry',
      'Pho',
      'Fried Chicken',
      'Steak',
      'Salad',
      'Ice Cream',
      'Chocolate',
      'Croissant',
      'Dumplings',
      'Lasagna',
      'Paella',
      'Falafel',
      'Shawarma',
      'Hummus',
      'Bibimbap',
      'Sashimi',
      'Poke Bowl',
      'Bagel',
      'Pancakes',
      'Waffles',
      'Clam Chowder',
      'Mac and Cheese',
      'Fajitas',
      'Chili',
      'Gumbo',
      'Ceviche',
      'Enchiladas',
      'Quesadilla',
      'Nachos',
      'Spring Rolls',
      'Egg Rolls',
      'Bao',
      'Banh Mi',
      'Kimchi',
      'Gimbap',
      'Takoyaki',
      'Okonomiyaki',
      'Tempura',
      'Paneer Tikka',
      'Biryani',
      'Dal',
      'Naan',
      'Shabu Shabu',
      'Hot Pot',
      'Fondue',
      'Poutine',
      'Arepa',
      'Empanada',
      'Feijoada',
      'Fish and Chips',
      'Shepherds Pie',
      'Quiche',
      'Crepes',
      'Miso Soup',
      'Gazpacho',
      'Bruschetta',
      'Caprese Salad',
      'Risotto',
      'Gnocchi',
      'Tiramisu',
      'Cheesecake',
      'Brownies',
      'Cupcakes',
      'Donuts',
      'Churros',
    ],
  },
  {
    id: 'animals',
    name: 'Animals',
    words: [
      'Lion',
      'Tiger',
      'Elephant',
      'Giraffe',
      'Zebra',
      'Kangaroo',
      'Panda',
      'Koala',
      'Dolphin',
      'Whale',
      'Shark',
      'Eagle',
      'Falcon',
      'Penguin',
      'Polar Bear',
      'Grizzly Bear',
      'Wolf',
      'Fox',
      'Cheetah',
      'Leopard',
      'Rhinoceros',
      'Hippopotamus',
      'Alligator',
      'Crocodile',
      'Chimpanzee',
      'Gorilla',
      'Orangutan',
      'Octopus',
      'Squid',
      'Sea Turtle',
      'Otter',
      'Moose',
      'Bison',
      'Buffalo',
      'Deer',
      'Antelope',
      'Gazelle',
      'Camel',
      'Llama',
      'Alpaca',
      'Goat',
      'Sheep',
      'Cow',
      'Pig',
      'Horse',
      'Donkey',
      'Mule',
      'Chicken',
      'Rooster',
      'Duck',
      'Goose',
      'Swan',
      'Peacock',
      'Parrot',
      'Macaw',
      'Cockatoo',
      'Owl',
      'Hawk',
      'Vulture',
      'Bat',
      'Hedgehog',
      'Porcupine',
      'Beaver',
      'Raccoon',
      'Skunk',
      'Possum',
      'Sloth',
      'Armadillo',
      'Iguana',
      'Chameleon',
      'Komodo Dragon',
      'Tortoise',
      'Frog',
      'Toad',
      'Salamander',
      'Newt',
      'Lobster',
      'Crab',
      'Shrimp',
      'Jellyfish',
      'Starfish',
      'Seahorse',
      'Manatee',
      'Narwhal',
      'Walrus',
      'Seal',
      'Sea Lion',
      'Hummingbird',
      'Flamingo',
      'Pelican',
      'Stork',
      'Toucan',
      'Crow',
      'Raven',
      'Pigeon',
      'Sparrow',
      'Robin',
      'Blue Jay',
      'Cardinal',
      'Turkey',
      'Emu',
      'Ostrich',
      'Kiwi',
      'Platypus',
      'Echidna',
      'Tasmanian Devil',
      'Meerkat',
      'Prairie Dog',
      'Weasel',
      'Ferret',
      'Mink',
      'Hyena',
      'Jackal',
      'Wild Boar',
    ],
  },
  {
    id: 'celebrities',
    name: 'Celebrities',
    words: [
      'Beyonce',
      'Taylor Swift',
      'Rihanna',
      'Ariana Grande',
      'Selena Gomez',
      'Katy Perry',
      'Lady Gaga',
      'Billie Eilish',
      'Ed Sheeran',
      'Bruno Mars',
      'The Weeknd',
      'Drake',
      'Kendrick Lamar',
      'J Cole',
      'Travis Scott',
      'Kanye West',
      'Jay-Z',
      'Eminem',
      'Justin Bieber',
      'Shawn Mendes',
      'Harry Styles',
      'Dua Lipa',
      'Olivia Rodrigo',
      'Doja Cat',
      'Bad Bunny',
      'Rosalia',
      'Shakira',
      'Jennifer Lopez',
      'Miley Cyrus',
      'Post Malone',
      'Snoop Dogg',
      'Ice Spice',
      'Nicki Minaj',
      'Cardi B',
      'Zendaya',
      'Tom Holland',
      'Chris Hemsworth',
      'Chris Evans',
      'Scarlett Johansson',
      'Robert Downey Jr.',
      'Ryan Reynolds',
      'Hugh Jackman',
      'Dwayne Johnson',
      'Jason Momoa',
      'Gal Gadot',
      'Margot Robbie',
      'Emma Stone',
      'Emma Watson',
      'Daniel Radcliffe',
      'Rupert Grint',
      'Timothee Chalamet',
      'Florence Pugh',
      'Zendaya',
      'Pedro Pascal',
      'Bella Ramsey',
      'Ana de Armas',
      'Keanu Reeves',
      'Matt Damon',
      'Ben Affleck',
      'Leonardo DiCaprio',
      'Brad Pitt',
      'Angelina Jolie',
      'Natalie Portman',
      'Anne Hathaway',
      'Viola Davis',
      'Meryl Streep',
      'Denzel Washington',
      'Tom Cruise',
      'Harrison Ford',
      'KSI',
      'Zerkaa',
      'Vikkstar123',
      'Tobjzl',
      'Behzinga',
      'W2S',
      'Miniminter',
      'Callux',
      'Ethan Payne',
      'Freezy',
      'Harry Lewis',
      'PewDiePie',
      'MrBeast',
      'Markiplier',
      'Jacksepticeye',
      'Ninja',
      'Shroud',
      'xQc',
      'Pokimane',
      'Valkyrae',
      'HasanAbi',
      'Ludwig',
      'TimTheTatman',
      'Dr Disrespect',
      'Sykkuno',
      'Disguised Toast',
      'Myth',
      'Tfue',
      'Nickmercs',
      'SypherPK',
      'Tyler1',
      'Imane Anys',
      'Rachell Hofstetter',
      'Valkyrae',
      'Corpse Husband',
      'Dream',
      'GeorgeNotFound',
      'Sapnap',
      'TommyInnit',
      'Tubbo',
      'Ranboo',
      'Wilbur Soot',
      'Quackity',
      'Karl Jacobs',
      'Foolish Gamers',
      'BadBoyHalo',
      'Skeppy',
      'Technoblade',
      'Philza',
      'CaptainSparklez',
      'DanTDM',
      'Stampy',
      'PopularMMOs',
      'SSundee',
      'PrestonPlayz',
      'UnspeakableGaming',
      'Jelly',
      'Crainer',
      'Logan Paul',
      'Jake Paul',
      'David Dobrik',
      'Emma Chamberlain',
      'Charli DAmelio',
      'Dixie DAmelio',
      'Addison Rae',
      'Zach King',
      'Liza Koshy',
      'Rudy Mancuso',
      'Lele Pons',
      'Casey Neistat',
      'Peter McKinnon',
      'MKBHD',
      'Linus Tech Tips',
      'iJustine',
      'Unbox Therapy',
      'Austin Evans',
      'Ludwig Ahgren',
      'Hasan Piker',
      'Amouranth',
      'Alinity',
      'Asmongold',
      'MoistCr1TiKaL',
      'Summit1g',
      'Sodapoppin',
      'Forsen',
      'Mizkif',
      'Maya',
      'Will Neff',
      'ConnorEatsPants',
      'Jschlatt',
      'Carson',
      'Ted Nivison',
      'Traves',
      'Cooper',
      'Noah Hugbox',
      'Joko',
      'Jake Doolittle',
      'Chandler Hallow',
      'Chris Tyson',
      'Karl Jacobs',
      'Nolan Hansen',
      'Jimmy Donaldson',
      'MrBeast Gaming',
      'Chandler',
      'Garrett',
      'Tareq',
      'Kris Tyson',
      'Dude Perfect',
      'Rhett and Link',
      'Smosh',
      'Good Mythical Morning',
      'The Try Guys',
      'Sidemen',
      'Duke Dennis',
      'Agent 00',
      'Fanum',
      'Kai Cenat',
      'IShowspeed',
      'Adin Ross',
    ],
  },
];

export const getCategoryById = (id: string) =>
  impostorCategories.find((category) => category.id === id);

